# Site settings
title: Software engineer | Kirill Bobrov
author: k1r8r0wn
description:
  Hi, I'm software engineer. Welcome to my personal blog.
keywords:
  internet web website page design development freelancer developer web-developer sortware-engineer front-end
  back-end ruby ruby-on-rails rspec jekyll postgresql html5 css3 bootstrap mailchimp javascript vuejs
  git russia saint-petersburg siberia omsk

heading-img: assets/img/sky.jpg

baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://k1r8r0wn.github' # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:title

# Posts pagination
paginate: 5
paginate_limit: 7

# Projects collection
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# GitHub's repository
# repository: k1r8r0wn/k1r8r0wn.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-coffeescript
